### ISSUE TITLE
gcc 7.5.0 compile error: invalid initialization of reference of type 'vsg::ImageInfo&' from expression of type 'vsg::ref_ptr<vsg::ImageInfo>'

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgUnity#6]
Compiling vsgUnity with recent vsg results into the following error:
```
[  136s] /home/abuild/rpmbuild/BUILD/vsgUnity-0.0.0+20211028+git.f988586/unity2vsg/src/unity2vsg/unity2vsg.cpp:47:41: 
  error: invalid initialization of reference of type 'vsg::ImageInfo&' from expression of type 'vsg::ref_ptr<vsg::ImageInfo>'
[  136s]                  if (auto data = getData(imageInfo))
[  136s]                                          ^~~~~~~~~
```
[_log.txt](https://github.com/vsg-dev/vsgUnity/files/7453756/_log.txt)

**Comment by rhabacker** [comment]
This is still an issue.

**Comment by rhabacker** [comment]
Is there any hint how to solve that compile issue ?

**Comment by robertosfield** [comment]
Sorry, missed checking vsgUnity.  ImageInfo changed from being a struct that you passed around to an object created on the heap with a ref_ptr<> passed back.

I will have a bash at getting it compile this morning.

**Comment by robertosfield** [comment]
I have checked in a number of build fixes so unity2vsg now compiles with VSG master.  I don't have time to get Unity back running on my machine this morning so would appreciate other diving in with testing.

**Comment by rhabacker** [comment]
Thanks. I can confirm, that is builds now again.
